# Minimal pnpm-audit-hook configuration
# Only essential options are included; defaults are used for everything else

policy:
  block:
    - critical
    - high
  warn:
    - medium
    - low
    - unknown

sources:
  osv: true

cache:
  ttlSeconds: 3600
